version: '3'
services:
 app:
    container_name: my_app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/db1
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"
 db:
    image: mariadb:10.11.6
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: db1
    volumes:
      - db:/var/lib/mysql
volumes:
 db:
