version: '3'
services:
 app:
    container_name: my_app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://172.17.0.2:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"
 db:
    image: mariadb:10.8.2
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: db1
    volumes:
      - db:/var/lib/mysql
volumes:
 db:
