version: '3'
services:
 wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:3306 -t 30s -i 250ms

 app:
    container_name: my_app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    ports:
      - "8080:8080"

 db:
    image: mariadb:10.8.2
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: db1
    volumes:
      - db:/var/lib/mysql
volumes:
 db:
